
/** type def for the req.files generated by multer parsing */
export type MulterFiles = { [filename: string]: Express.Multer.File[] } | Express.Multer.File[];

/** function type for the handler methods to be invoked by the plex controller */
export type PlexHandlerFunction = (payload: any, files: MulterFiles) => Promise<void>;

/** class container and wrapper for the handler methods to be invoked by the plex controller */
export class PlexHandler {
  handler: PlexHandlerFunction;

  /**
   * Constructor fro the wrappper/container for user defined plex handlers.
   * @param handler the PlexHandlerFunction to be invoked
   */
  public constructor(handler: PlexHandlerFunction) {
    this.handler = handler;
  }

  /**
   * Execute the PlexHandlerFunction.
   * @param payload 
   * @param files 
   */
  public async execute(payload: any, files: MulterFiles): Promise<void> {
    return await this.handler(payload, files);
  }

}
